### ISSUE TITLE
max_concurrency support

### ISSUE THREAD

**Issue by lorenzo132** [Deivu/Indomitable#1]
Would it be possible so this sharding manager will make use of the max_concurrency limit when this is enabled for a bot

**Comment by Deivu** [comment]
Very possible, since I introduced waitForReady, but that is on websocket shard modifications, and while Indomitable can work with it, I don't plan adding support for it yet, but I know it can work since I added support on it on 2 bots which is Chip and Kashima which uses Indomitable as their sharder
